### PR TITLE
kola: Add YAML description with error message to TAP file

### PR DESCRIPTION
**Pull request by pothos**
The TAP file is not useful if the console logs are lost because the
TAP files does not contain the error message.
Add a YAML description to the TAP file as understood by the Jenkins
TAP plugin. For now it only contains the test's error message as value
for the "Error" entry.

# How to use/test

```
# change platform/platform.go:
  sshRetries = 5
  sshTimeout = 5 * time.Second
$ make
$ cd bin
$ sudo ./kola run -d --qemu-skip-mangle --qemu-image flatcar_production_qemu_image.img
$ # while running and the first tests passed, corrupt the image file by overwriting it with a used one:
$ cp flatcar_production_qemu_image_something_that_got_booted_before.img flatcar_production_qemu_image.img
$ tail -f _kola_temp/qemu-latest/test.tap  # watch entries for passed and failed tests
1..57
ok - cl.ignition.v2_1.swap
not ok - cl.filesystem
  ---
  Error: "        harness.go:515: Cluster failed starting machines: machine \"0c095b84-2469-4c1b-bba5-288744fa4038\" failed basic checks: some systemd units failed:\nuser@500.service loaded failed failed User Manager for UID 500\n"
  ...
not ok - docker.base
  ---
  Error: "        harness.go:515: Cluster failed starting machines: machine \"fbc56b90-a152-452a-b7d7-1379a6b9c616\" failed to start: ssh journalctl failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain\n"
  ...
not ok - linux.nfs.v3
  ---
  Error: "        nfs.go:79: Cluster.NewMachine: machine \"ca9d1c3d-8d87-46ff-a277-aaaa534ea578\" failed to start: ssh journalctl failed: ssh: handshake failed: read tcp 10.0.0.1:51168->10.0.0.6:22: read: connection reset by peer\n        harness.go:485: Found kernel panic (Attempted to kill init! exitcode=0x00000007\r) on machine ca9d1c3d-8d87-46ff-a277-aaaa534ea578 console\n        harness.go:485: Found core dump on machine ca9d1c3d-8d87-46ff-a277-aaaa534ea578 console\n"
  ...
not ok - cl.disk.raid.root
  ---
  Error: "        raid.go:128: machine \"fab37f4b-412a-43e9-bc55-06b4e4fceffc\" failed to start: ssh journalctl failed: dial tcp 10.0.0.7:22: connect: connection refused\n"
  ...
ok - cl.ignition.v1.once
ok - linux.nfs.v4
ok - coreos.ignition.groups
[…]
```

### CODE REVIEW

**Comment by t-lo** [comment]
I've gotten this far, too, with a slightly different implementation (I was capturing the error message in https://github.com/flatcar-linux/mantle/blob/flatcar-master/harness/harness.go#L249-L270 and then stored it in an additional `errorMsg` string in the `Harness` struct to be used in `flushToParent).

However, this fails for `NativeTest` tests (i.e. all of `coretest`). If you e.g. add `return fmt.Errorf(" test error ") ` to `TestSymlinkFlatcar` (https://github.com/flatcar-linux/mantle/blob/flatcar-master/kola/tests/coretest/core.go#L256) and run `cl.basic` tests then the output breaks:

```
cat report.tap 
1..1
not ok - cl.basic
  ---
  Error: "    --- PASS: cl.basic/RandomUUID (0.12s)\n    --- PASS: cl.basic/Useradd (0.14s)\n    --- PASS: cl.basic/CloudConfig (0.35s)\n    --- PASS: cl.basic/DbusPerms (0.19s)\n    --- PASS: cl.basic/Symlink (0.12s)\n        cluster.go:75: kolet:\n2020-04-01T17:11:50Z kolet:  test error\n    --- FAIL: cl.basic/SymlinkFlatcar (0.10s)\n            cluster.go:78: kolet: Process exited with status 1\n    --- PASS: cl.basic/UpdateEngineKeys (0.13s)\n    --- PASS: cl.basic/ServicesActive (0.18s)\n    --- PASS: cl.basic/Script (0.14s)\n    --- PASS: cl.basic/PortSSH (0.11s)\n    --- PASS: cl.basic/ReadOnly (0.10s)\n    --- PASS: cl.basic/MachineID (0.12s)\n"
  ...
```

Most ironically I tested with `cl.basic` from the beginning, this is where I got stuck.

**Comment by pothos** [comment]
Good catch, I've filtered the passed subtests away because they just add noise.

**Comment by t-lo** [comment]
Filtering seems like a good approach but might still include output from (passed) tests.

How much effort do you think would it take to capture the actual fail output of native tests from here: https://github.com/flatcar-linux/mantle/blob/kai/add-tap-yaml-description/kola/cluster/cluster.go#L57-L81 and provide it to he TAP writing function in `harness/harness.go`?

**Comment by pothos** [comment]
Seems possible, too. I don't know how many things would need to change for that.

I added a second regex to remove the any output lines after `--- PASS:` up to next `--- FAIL:`.

**Comment by pothos** [comment]
Ok, then I'll merge now and we can revisit this later and make bigger changes to fit our needs.

**Pull request merged**
